VERSION = 0.2.3
# Paths
M_PREFIX = /usr
M_INSTALL_BIN = $$INSTALL_ROOT$$M_PREFIX/bin/
M_INSTALL_DATA = $$INSTALL_ROOT$$M_PREFIX/share/
M_THEME_DIR = $$M_INSTALL_DATA/themes/
TARGET = meego-handset-chat

